"""The command line, as the manual's Command line page reads it.

That page is generated by walking `build_parser()` (`tools/gen_doc_pages.py`),
which is what keeps it from disagreeing with the command it documents. The
generator can only print what the parser carries, so a verb added without
`help=` becomes a blank row rather than a build failure — documentation that
is quietly incomplete rather than loudly missing.

These tests are that build failure.
"""

import argparse

from xams_sc.cli import xams_ctl


def subcommands():
    parser = xams_ctl.build_parser()
    action = next(a for a in parser._actions
                  if isinstance(a, argparse._SubParsersAction))
    helps = {c.dest: c.help for c in action._choices_actions}
    return action.choices, helps


class TestEveryCommandDocumentsItself:
    def test_every_verb_has_help(self):
        choices, helps = subcommands()

        missing = sorted(name for name in choices if not helps.get(name))
        assert not missing, f"no help= on: {', '.join(missing)}"

    def test_every_argument_has_help(self):
        choices, _ = subcommands()

        missing = []
        for name, parser in choices.items():
            for action in parser._actions:
                if isinstance(action, argparse._HelpAction):
                    continue
                if not action.help:
                    missing.append(f"{name} {action.dest}")
        assert not missing, f"no help= on: {', '.join(sorted(missing))}"

    def test_the_global_options_have_help(self):
        parser = xams_ctl.build_parser()

        missing = [a.dest for a in parser._actions
                   if a.option_strings and not isinstance(a, argparse._HelpAction)
                   and not a.help]
        assert not missing, f"no help= on: {', '.join(missing)}"


class TestEveryCommandStillRuns:
    def test_each_verb_is_wired_to_a_function(self):
        """A subcommand with no `func` raises AttributeError in `main` — at
        the moment somebody runs it, which on this system is the moment
        something has already gone wrong."""
        choices, _ = subcommands()
        parser = xams_ctl.build_parser()

        for name in choices:
            args = parser.parse_args([name] + _placeholder_args(name))
            assert callable(getattr(args, "func", None)), \
                f"{name} is not wired to a command function"


def _placeholder_args(name: str) -> list[str]:
    """The required positionals, for verbs that have any."""
    return {"hv-set": ["hv_cathode_vset", "-2250"],
            "hv-clear-trip": ["hv_cathode_vset"]}.get(name, [])
